name: Test
on: 
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup User and RDP Environment
      run: |
        
        sudo apt update
        sudo apt install -y --no-install-recommends i3-wm i3status i3lock xterm xrdp xorgxrdp dbus-x11 x11-xserver-utils kitty

        sudo useradd -m -s /bin/bash Sora
        echo "Sora:kali" | sudo chpasswd
        sudo usermod -aG sudo Sora

        sudo bash -c 'cat > /home/Sora/.xsession <<EOF
        export XDG_SESSION_TYPE=x11
        export XDG_CURRENT_DESKTOP=i3
        exec dbus-launch --exit-with-session i3
        EOF'
        sudo chown Sora:Sora /home/Sora/.xsession

        sudo bash -c 'cat > /home/Sora/.xsession <<EOF
        export HOME=/home/Sora
        export XDG_CONFIG_HOME=/home/Sora/.config
        export XDG_SESSION_TYPE=x11
        export XDG_CURRENT_DESKTOP=i3
        exec dbus-launch --exit-with-session i3
        EOF'
      
        sudo bash -c 'cat > /etc/xrdp/startwm.sh <<EOF
        #!/bin/sh
        if [ -r /etc/default/locale ]; then
        . /etc/default/locale
          export LANG LANGUAGE
        fi
        exec /etc/X11/Xsession
        EOF'
        sudo chmod +x /etc/xrdp/startwm.sh
        sudo systemctl restart xrdp
    
        # 6. Restart Everything
        #sudo systemctl enable xrdp
        #sudo systemctl restart xrdp
        
        # 4. Open Firewall (ufw is the standard Ubuntu firewall)
        sudo ufw allow 3389/tcp

    - name: Cloudflare Tunnel (Linux Setup)
      run: |
        echo "=== Cloudflare Tunnel ==="
        # Download the .deb package for Ubuntu
        curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -o cloudflared.deb
        sudo dpkg -i cloudflared.deb
        
        # Install the service with your token
        sudo cloudflared service install eyJhIjoiZjhkNzdkY2U2ZmNjM2MyNDE3OTI5MTJiYzk4OWY3ZjYiLCJ0IjoiZDU1YzcxMmUtNjZhZi00OTNjLTg3ZGUtNjNiOGQ1YjNlN2Y2IiwicyI6IlpEY3pNV1ZoWWpNdE16aGhZUzAwT0dRM0xUazBObUV0WkdJd01EWTFNakk0WWpOaCJ9
        
        # Check status
        systemctl status cloudflared
    - name: Keep Alive
      timeout-minutes: 360
      run: sleep 21600
      
